// Generated by `wit-bindgen` 0.36.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_register_routes_cabi<T: Guest>() {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    T::register_routes();
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_network_add_cabi<T: Guest>(arg0: *mut u8, arg1: usize) {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    T::network_add(_rt::string_lift(bytes0));
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_network_set_chain_id_cabi<T: Guest>(arg0: *mut u8, arg1: usize) {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    T::network_set_chain_id(_rt::string_lift(bytes0));
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_network_set_gas_price_cabi<T: Guest>(arg0: *mut u8, arg1: usize) {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    T::network_set_gas_price(_rt::string_lift(bytes0));
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_networks_all_cabi<T: Guest>(arg0: *mut u8, arg1: usize) {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    T::networks_all(_rt::string_lift(bytes0));
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_wallet_add_cabi<T: Guest>(arg0: *mut u8, arg1: usize) {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    T::wallet_add(_rt::string_lift(bytes0));
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_wallet_add_network_cabi<T: Guest>(arg0: *mut u8, arg1: usize) {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    T::wallet_add_network(_rt::string_lift(bytes0));
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_wallet_address_cabi<T: Guest>(arg0: *mut u8, arg1: usize) {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    T::wallet_address(_rt::string_lift(bytes0));
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_wallet_public_key_cabi<T: Guest>(arg0: *mut u8, arg1: usize) {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    T::wallet_public_key(_rt::string_lift(bytes0));
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_wallet_balance_cabi<T: Guest>(arg0: *mut u8, arg1: usize) {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    T::wallet_balance(_rt::string_lift(bytes0));
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_wallet_networks_cabi<T: Guest>(arg0: *mut u8, arg1: usize) {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    T::wallet_networks(_rt::string_lift(bytes0));
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_wallet_transfer_cabi<T: Guest>(arg0: *mut u8, arg1: usize) {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    T::wallet_transfer(_rt::string_lift(bytes0));
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_wallet_deploy_contract_cabi<T: Guest>(arg0: *mut u8, arg1: usize) {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    T::wallet_deploy_contract(_rt::string_lift(bytes0));
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_wallet_call_contract_cabi<T: Guest>(arg0: *mut u8, arg1: usize) {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    T::wallet_call_contract(_rt::string_lift(bytes0));
}
pub trait Guest {
    fn register_routes();
    fn network_add(cmd: _rt::String);
    fn network_set_chain_id(cmd: _rt::String);
    fn network_set_gas_price(cmd: _rt::String);
    fn networks_all(cmd: _rt::String);
    fn wallet_add(cmd: _rt::String);
    fn wallet_add_network(cmd: _rt::String);
    fn wallet_address(cmd: _rt::String);
    fn wallet_public_key(cmd: _rt::String);
    fn wallet_balance(cmd: _rt::String);
    fn wallet_networks(cmd: _rt::String);
    fn wallet_transfer(cmd: _rt::String);
    fn wallet_deploy_contract(cmd: _rt::String);
    fn wallet_call_contract(cmd: _rt::String);
}
#[doc(hidden)]
macro_rules! __export_world_evm_wallet_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[export_name = "register-routes"] unsafe extern "C" fn
        export_register_routes() { $($path_to_types)*::
        _export_register_routes_cabi::<$ty > () } #[export_name = "network-add"] unsafe
        extern "C" fn export_network_add(arg0 : * mut u8, arg1 : usize,) {
        $($path_to_types)*:: _export_network_add_cabi::<$ty > (arg0, arg1) }
        #[export_name = "network-set-chain-id"] unsafe extern "C" fn
        export_network_set_chain_id(arg0 : * mut u8, arg1 : usize,) {
        $($path_to_types)*:: _export_network_set_chain_id_cabi::<$ty > (arg0, arg1) }
        #[export_name = "network-set-gas-price"] unsafe extern "C" fn
        export_network_set_gas_price(arg0 : * mut u8, arg1 : usize,) {
        $($path_to_types)*:: _export_network_set_gas_price_cabi::<$ty > (arg0, arg1) }
        #[export_name = "networks-all"] unsafe extern "C" fn export_networks_all(arg0 : *
        mut u8, arg1 : usize,) { $($path_to_types)*:: _export_networks_all_cabi::<$ty >
        (arg0, arg1) } #[export_name = "wallet-add"] unsafe extern "C" fn
        export_wallet_add(arg0 : * mut u8, arg1 : usize,) { $($path_to_types)*::
        _export_wallet_add_cabi::<$ty > (arg0, arg1) } #[export_name =
        "wallet-add-network"] unsafe extern "C" fn export_wallet_add_network(arg0 : * mut
        u8, arg1 : usize,) { $($path_to_types)*:: _export_wallet_add_network_cabi::<$ty >
        (arg0, arg1) } #[export_name = "wallet-address"] unsafe extern "C" fn
        export_wallet_address(arg0 : * mut u8, arg1 : usize,) { $($path_to_types)*::
        _export_wallet_address_cabi::<$ty > (arg0, arg1) } #[export_name =
        "wallet-public-key"] unsafe extern "C" fn export_wallet_public_key(arg0 : * mut
        u8, arg1 : usize,) { $($path_to_types)*:: _export_wallet_public_key_cabi::<$ty >
        (arg0, arg1) } #[export_name = "wallet-balance"] unsafe extern "C" fn
        export_wallet_balance(arg0 : * mut u8, arg1 : usize,) { $($path_to_types)*::
        _export_wallet_balance_cabi::<$ty > (arg0, arg1) } #[export_name =
        "wallet-networks"] unsafe extern "C" fn export_wallet_networks(arg0 : * mut u8,
        arg1 : usize,) { $($path_to_types)*:: _export_wallet_networks_cabi::<$ty > (arg0,
        arg1) } #[export_name = "wallet-transfer"] unsafe extern "C" fn
        export_wallet_transfer(arg0 : * mut u8, arg1 : usize,) { $($path_to_types)*::
        _export_wallet_transfer_cabi::<$ty > (arg0, arg1) } #[export_name =
        "wallet-deploy-contract"] unsafe extern "C" fn export_wallet_deploy_contract(arg0
        : * mut u8, arg1 : usize,) { $($path_to_types)*::
        _export_wallet_deploy_contract_cabi::<$ty > (arg0, arg1) } #[export_name =
        "wallet-call-contract"] unsafe extern "C" fn export_wallet_call_contract(arg0 : *
        mut u8, arg1 : usize,) { $($path_to_types)*::
        _export_wallet_call_contract_cabi::<$ty > (arg0, arg1) } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_evm_wallet_cabi;
#[rustfmt::skip]
mod _rt {
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub use alloc_crate::string::String;
    extern crate alloc as alloc_crate;
}
/// Generates `#[no_mangle]` functions to export the specified type as the
/// root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_evm_wallet_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_evm_wallet_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_evm_wallet_impl as export;
#[cfg(target_arch = "wasm32")]
#[link_section = "component-type:wit-bindgen:0.36.0:component:evm-wallet:evm-wallet:encoded world"]
#[doc(hidden)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 480] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xdf\x02\x01A\x02\x01\
A\x10\x01@\0\x01\0\x04\0\x0fregister-routes\x01\0\x01@\x01\x03cmds\x01\0\x04\0\x0b\
network-add\x01\x01\x04\0\x14network-set-chain-id\x01\x01\x04\0\x15network-set-g\
as-price\x01\x01\x04\0\x0cnetworks-all\x01\x01\x04\0\x0awallet-add\x01\x01\x04\0\
\x12wallet-add-network\x01\x01\x04\0\x0ewallet-address\x01\x01\x04\0\x11wallet-p\
ublic-key\x01\x01\x04\0\x0ewallet-balance\x01\x01\x04\0\x0fwallet-networks\x01\x01\
\x04\0\x0fwallet-transfer\x01\x01\x04\0\x16wallet-deploy-contract\x01\x01\x04\0\x14\
wallet-call-contract\x01\x01\x04\0\x1fcomponent:evm-wallet/evm-wallet\x04\0\x0b\x10\
\x01\0\x0aevm-wallet\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-comp\
onent\x070.220.1\x10wit-bindgen-rust\x060.36.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
